In [1]:
%matplotlib notebook
import chaospy as cp
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from numpy import linalg as LA
import pandas as pd
import seaborn as sns
import itertools


In [2]:
def foo2(coord, param):
    return param[0] * np.e ** (-param[1] * coord)
def foo1(coord, param):
    return param * np.e ** (-param * coord)

In [17]:
coord = np.linspace(0,10,100)
dist = cp.J(cp.Uniform(1,2), cp.Uniform(1,2))
# dist = cp.Uniform(1,2)
dist_normal = cp.Normal(0,1)
dist_gamma = cp.Gamma()


In [20]:
print(dir(dist_gamma))
print(dist_gamma.)

['__add__', '__array_priority__', '__class__', '__delattr__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__pow__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmul__', '__rpow__', '__rsub__', '__rtruediv__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '_bnd', '_cdf', '_dep', '_mom', '_pdf', '_ppf', '_str', '_ttr', 'addattr', 'advance', 'cdf', 'dependencies', 'dependent', 'fwd', 'graph', 'inv', 'length', 'mom', 'pdf', 'prm', 'range', 'sample', 'ttr']


In [16]:
# x,w = cp.generate_quadrature(2,dist_normal)
# print(x,w)
coord1d, weight1d = cp.generate_quadrature(2,dist_normal)
print(coord1d, weight1d)
coord1d, weight1d = np.polynomial.hermite_e.hermegauss(3)  # “Probabilists’"
print(coord1d, weight1d)
coord1d, weight1d = np.polynomial.hermite.hermgauss(3) 
print(coord1d, weight1d)

[[-7.5  0.   7.5]] [0.16666667 0.66666667 0.16666667]
[-1.73205081  0.          1.73205081] [0.41777138 1.67108552 0.41777138]
[-1.22474487  0.          1.22474487] [0.29540898 1.1816359  0.29540898]


In [39]:
a = np.arange(9).reshape((3,3))
print(a)
print(a.shape)
for ia in a:
    print(ia)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
[0 1 2]
[3 4 5]
[6 7 8]


In [27]:
# samples = dist.sample(50)
# evals = np.array([foo(coord, sample) for sample in samples.T]).T
# plt.plot(coord, evals)
# plt.show()
# evals = [foo(coord, sample) for sample in samples.T]

orthPoly = cp.orth_ttr(3, dist)
print(orthPoly.dim)
print(len(orthPoly))

# # Monte Carlo simulaiton

samples = dist.sample(1000, 'H')
print('{}:{}'.format('samples shape',samples.shape))
evals = np.array([foo2(coord, sample) for sample in samples.T])
# print(np.array(foo(coord, [0.5,0.5])).shape)
print(evals.shape)
# expected = np.mean(evals,0)
# deviation = np.std(evals,0)

# # Point Collocation method

# foo_hat = cp.fit_regression(orthPoly, samples, evals)
foo_hat, _coefffs = cp.fit_regression(orthPoly, samples, evals[:,50:53], retall=True)
print('_coefffs shape: {}'.format(_coefffs.shape))
print('len(foo_hat): {}'.format(len(foo_hat)))
# print(_coefffs[:,0])
# print(len(foo_hat[0]))
# print(foo_hat[0].coeffs(),'\n',foo_hat[1].coeffs())
# print(dir(foo_hat[0]))
# print('_coefffs:{}'.format(_coefffs))
# print('coeffs:\n{}'.format(foo_hat.coeffs()))
# print('dim:\n{}'.format(foo_hat.dim))
# print('keys:\n{}'.format(foo_hat.keys))
# print('shape:\n{}'.format(foo_hat.shape))
# print(len(foo_hat))
foo_hat0 = foo_hat

print(cp.around(foo_hat0, 3))

print('foo_hat0.dim = {}'.format(foo_hat0.dim))
y = np.array([foo_hat(*isample) for isample in samples.T])
print(y)
print(cp.around((foo_hat0())))

y = foo_hat0(samples.T)
y = np.array([foo_hat0(*isample) for isample in samples.T])
print('y.shape = {}'.format(y.shape))
print(y)

# print(samples.shape)
y = foo_hat(*samples)
print(y)

## how to print coeffs

# # Pseudo-spectral Projection

# x,w = cp.generate_quadrature(8,dist,rule='C')
# evals = [foo(coord, val) for val in x.T]
# # foo_hat = cp.fit_quadrature(orthPoly, x, w, evals)

# print(x.shape)
# print(w.shape)
# print(np.asarray(evals).shape)
# y_hat = foo_hat(*samples)
# print(y_hat.shape)


# cp.seed(1000)
# dist = cp.Normal()
# x = cp.variable(1)
# poly = cp.Poly([x,x**2])
# print(poly)
# qoi_dist = cp.QoI_Dist(poly, dist)


2
10
samples shape:(2, 1000)
(1000, 100)
_coefffs shape: (10, 3)
len(foo_hat): 3
[0.01q0q1^2-0.023q1^3-0.035q0q1+0.105q1^2+0.03q0-0.154q1+0.074, 0.009q0q1^2-0.022q1^3-0.032q0q1+0.097q1^2+0.027q0-0.143q1+0.068, 0.008q0q1^2-0.02q1^3-0.029q0q1+0.09q1^2+0.024q0-0.132q1+0.063]
foo_hat0.dim = 2
[[0.00060844 0.0005146  0.00043438]
 [0.00031415 0.00027439 0.00024035]
 [0.00295548 0.0026177  0.00231871]
 ...
 [0.00034483 0.00029355 0.00025016]
 [0.00473041 0.00423099 0.00378455]
 [0.00101559 0.00086433 0.00073466]]
[0.0, 0.0, 0.0]
y.shape = (1000, 3)
[[0.00060844 0.0005146  0.00043438]
 [0.00031415 0.00027439 0.00024035]
 [0.00295548 0.0026177  0.00231871]
 ...
 [0.00034483 0.00029355 0.00025016]
 [0.00473041 0.00423099 0.00378455]
 [0.00101559 0.00086433 0.00073466]]
[[0.00060844 0.00031415 0.00295548 ... 0.00034483 0.00473041 0.00101559]
 [0.0005146  0.00027439 0.0026177  ... 0.00029355 0.00423099 0.00086433]
 [0.00043438 0.00024035 0.00231871 ... 0.00025016 0.00378455 0.00073466]]


In [56]:
def foo(x):
    return 0.5*x[0] **2 - 3*x[1] **3

In [57]:
x = np.array([np.linspace(0,10,100),np.linspace(0,10,100)])
dist_x = cp.J(cp.Normal(0,1),cp.Normal(0,1))
dist_zeta = cp.J(cp.Normal(),cp.Normal())

orthPoly = cp.orth_ttr(3, dist_x)
print(orthPoly.dim)

# # Monte Carlo simulaiton

samples = dist_x.sample(1000, 'H')
print(samples.shape)
# evals = [foo(sample) for sample in samples.T]
evals = foo(samples)
# print(np.array(foo(coord, [0.5,0.5])).shape)
print(np.array(evals).shape)
# expected = np.mean(evals,0)
# deviation = np.std(evals,0)

# # Point Collocation method

# foo_hat = cp.fit_regression(orthPoly, samples, evals)
foo_hat, _coefffs = cp.fit_regression(orthPoly, samples, evals, retall=True)
print('_coefffs shape: {}'.format(_coefffs.shape))
print(_coefffs)
print(len(foo_hat))
print(foo_hat.coeffs())
print(dir(foo_hat))

2
(2, 1000)
(1000,)
_coefffs shape: (10, 1)
[[ 5.00000000e-01]
 [-9.00000000e+00]
 [ 5.21804822e-15]
 [ 1.55431223e-15]
 [ 6.66133815e-16]
 [ 5.00000000e-01]
 [-3.00000000e+00]
 [ 1.05471187e-15]
 [ 2.22044605e-16]
 [ 8.88178420e-16]]
1
[ 1.55431223e-15  3.33066907e-15  1.49880108e-15  1.55431223e-15
  6.66133815e-16 -3.00000000e+00  1.05471187e-15  5.00000000e-01
  2.22044605e-16  8.88178420e-16]
['A', '__abs__', '__add__', '__array_priority__', '__call__', '__class__', '__contains__', '__delattr__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__pos__', '__pow__', '__radd__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__rsub__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__wea

In [14]:
doe_samples = np.array([x,w])
print(doe_samples.shape)

(2,)


In [15]:
numList = ['1', '2', '3', '4']
seperator = ', '
print(seperator.join(numList))

1, 2, 3, 4
