In [1]:
%matplotlib notebook
import chaospy as cp
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from numpy import linalg as LA
import pandas as pd
import seaborn as sns
import itertools
import scipy.stats as stats


In [2]:
def foo2(coord, param):
    return param[0] * np.e ** (-param[1] * coord)
def foo1(coord, param):
    return param * np.e ** (-param * coord)

In [2]:
z = np.arange(10)
d = np.array([z,z])
print(d.shape)

(2, 10)


In [21]:
mu_Hs    = 0.77
sigma_Hs = 0.6565
Hs_shape = 1.503
Hs_scale = 2.691
h0       = 2.9
x        = 10
dist1    = cp.LogNormal(mu_Hs, sigma_Hs)

samples1 = np.random.lognormal(mu_Hs, sigma_Hs, x)
samples2 = np.random.weibull(Hs_shape,x) * Hs_scale
samples0 = np.where(samples1<=h0,samples1, samples2)
cdf_h0   = dist1.cdf(h0)
print(np.around(samples1,2))
print(np.around(samples2,2))
print(np.around(samples0,2))
print(cdf_h0)



[3.63 0.92 2.43 3.47 1.65 2.1  4.49 2.96 2.84 0.36]
[1.93 1.61 3.16 1.97 2.35 6.23 1.82 3.14 2.14 2.25]
[1.93 0.92 2.43 1.97 1.65 2.1  1.82 3.14 2.84 0.36]
0.6732524353557928


In [24]:

dist_u = cp.Uniform(0,1)
u_samples1 = dist_u.sample(100)
u_samples2 = dist_u.sample(100)
u9 = np.array([u_samples1,u_samples2])
print(dir(dist_u))

['__add__', '__array_priority__', '__class__', '__delattr__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__pow__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmul__', '__rpow__', '__rsub__', '__rtruediv__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '_bnd', '_cdf', '_fwd_cache', '_inv_cache', '_mom', '_pdf', '_ppf', '_repr', '_ttr', 'cdf', 'fwd', 'inv', 'mom', 'pdf', 'prm', 'range', 'sample', 'ttr']


In [7]:
def dist_Hs(Hs):
    mu_Hs    = 0.77
    simga_Hs = 0.6565
    dist_Hs1 = cp.LogNormal(mu_Hs, simga_Hs)
    Hs_shape = 1.503
    Hs_scale = 2.691
    dist_Hs2 = cp.Weibull(Hs_shape,Hs_scale)
    if Hs <= 2.9:
        return dist_Hs1
    else:
        return dist_Hs2
def dist_Tp(Hs):
    a1 = 1.134
    a2 = 0.892
    a3 = 0.225
    b1 = 0.005
    b2 = 0.120
    b3 = 0.455
    mu_tp = a1 + a2* Hs**a3 
    sigma_tp = np.sqrt(b1 + b2*np.exp(-b3*Hs))
    return cp.LogNormal(mu_tp, sigma_tp)

    

In [3]:
coord = np.linspace(0,10,100)
dist = cp.J(cp.Uniform(1,2), cp.Uniform(1,2))
# dist = cp.Uniform(1,2)
dist_normal = cp.Normal(0,1)
dist_gamma = cp.Gamma()


In [21]:
def coefficients(self):
    """Polynomial coefficients."""
    out = np.array([self.A[key] for key in self.keys])
    out = np.rollaxis(out, -1)
    return out

In [25]:
poly, norm = cp.orth_ttr(2, cp.Normal(), retall=True)
print(poly)
print(norm)
print(coefficients(poly))
# print(poly[2].coeffs())
# print(dir(poly))


[1.0, q0, q0^2-1.0]
[1. 1. 2.]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-1.  0.  1.]]


In [13]:
print(cp.Poly({(1,): np.array(1)}))
x, y = cp.variable(2)
print(x**2 + x*y + 2)
poly = -3*x + x**2 + y
print(poly.coefficients())

q0
q0^2+q0q1+2


AttributeError: 'Poly' object has no attribute 'coefficients'

In [5]:
# x,w = cp.generate_quadrature(2,dist_normal)
# print(x,w)
coord1d, weight1d = cp.generate_quadrature(2,dist_normal)
print(coord1d, weight1d)
coord1d, weight1d = np.polynomial.hermite_e.hermegauss(3)  # “Probabilists’"
print(coord1d, weight1d)
coord1d, weight1d = np.polynomial.hermite.hermgauss(3) 
print(coord1d, weight1d)

[[-7.5  0.   7.5]] [0.16666667 0.66666667 0.16666667]
[-1.73205081  0.          1.73205081] [0.41777138 1.67108552 0.41777138]
[-1.22474487  0.          1.22474487] [0.29540898 1.1816359  0.29540898]


In [6]:
a = np.arange(9).reshape((3,3))
print(a)
print(a.shape)
for ia in a:
    print(ia)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
[0 1 2]
[3 4 5]
[6 7 8]


In [42]:
# samples = dist.sample(50)
# evals = np.array([foo(coord, sample) for sample in samples.T]).T
# plt.plot(coord, evals)
# plt.show()
# evals = [foo(coord, sample) for sample in samples.T]

orthPoly = cp.orth_ttr(3, dist)
# print(orthPoly.dim)
# print(len(orthPoly))

# # Monte Carlo simulaiton

samples = dist.sample(1000, 'H')
# print('{}:{}'.format('samples shape',samples.shape))
evals = np.array([foo2(coord, sample) for sample in samples.T])
# print(np.array(foo(coord, [0.5,0.5])).shape)
# print(evals.shape)
# expected = np.mean(evals,0)
# deviation = np.std(evals,0)

# # Point Collocation method

# foo_hat = cp.fit_regression(orthPoly, samples, evals)
foo_hat, _coefffs = cp.fit_regression(orthPoly, samples, evals[:,50:53], retall=True)
# print('_coefffs shape: {}'.format(_coefffs.shape))
# print('len(foo_hat): {}'.format(len(foo_hat)))
# print(_coefffs[:,0])
# print(len(foo_hat[0]))
# print(foo_hat[0].coeffs(),'\n',foo_hat[1].coeffs())
# print(dir(foo_hat[0]))
print(foo_hat[0])
print('_coefffs:\n{}'.format(np.around(_coefffs[:,0],4)))
print('coeffs:\n{}'.format(np.around(foo_hat.coeffs()[0],4)))
# print('dim:\n{}'.format(foo_hat.dim))
# print('keys:\n{}'.format(foo_hat.keys))
# print('shape:\n{}'.format(foo_hat.shape))
# print(len(foo_hat))
# foo_hat0 = foo_hat

# print(cp.around(foo_hat0, 3))

# print('foo_hat0.dim = {}'.format(foo_hat0.dim))
# y = np.array([foo_hat(*isample) for isample in samples.T])
# print(y)
# print(cp.around((foo_hat0())))

# y = foo_hat0(samples.T)
# y = np.array([foo_hat0(*isample) for isample in samples.T])
# print('y.shape = {}'.format(y.shape))
# print(y)

# # print(samples.shape)
# y = foo_hat(*samples)
# print(y)

# # how to print coeffs

# # Pseudo-spectral Projection

# x,w = cp.generate_quadrature(8,dist,rule='C')
# evals = [foo(coord, val) for val in x.T]
# # foo_hat = cp.fit_quadrature(orthPoly, x, w, evals)

# print(x.shape)
# print(w.shape)
# print(np.asarray(evals).shape)
# y_hat = foo_hat(*samples)
# print(y_hat.shape)


# cp.seed(1000)
# dist = cp.Normal()
# x = cp.variable(1)
# poly = cp.Poly([x,x**2])
# print(poly)
# qoi_dist = cp.QoI_Dist(poly, dist)


-5.918738058796369e-05q0^3-2.088826362946916e-05q0^2q1+0.0003096813295569256q0^2+0.010181960263414934q0q1^2-0.02342562442803808q1^3-0.03515917985671702q0q1+0.10530739328052241q1^2+0.029817592156953343q0-0.15432263300551433q1+0.07382176526837383
_coefffs:
[ 0.0019 -0.007   0.0013  0.0152 -0.0047  0.     -0.0234  0.0102 -0.
 -0.0001]
coeffs:
[ 7.380e-02 -1.543e-01  2.980e-02  1.053e-01 -3.520e-02 -2.340e-02
  1.020e-02  3.000e-04 -0.000e+00 -1.000e-04]


In [56]:
def foo(x):
    return 0.5*x[0] **2 - 3*x[1] **3

In [57]:
x = np.array([np.linspace(0,10,100),np.linspace(0,10,100)])
dist_x = cp.J(cp.Normal(0,1),cp.Normal(0,1))
dist_zeta = cp.J(cp.Normal(),cp.Normal())

orthPoly = cp.orth_ttr(3, dist_x)
print(orthPoly.dim)

# # Monte Carlo simulaiton

samples = dist_x.sample(1000, 'H')
print(samples.shape)
# evals = [foo(sample) for sample in samples.T]
evals = foo(samples)
# print(np.array(foo(coord, [0.5,0.5])).shape)
print(np.array(evals).shape)
# expected = np.mean(evals,0)
# deviation = np.std(evals,0)

# # Point Collocation method

# foo_hat = cp.fit_regression(orthPoly, samples, evals)
foo_hat, _coefffs = cp.fit_regression(orthPoly, samples, evals, retall=True)
print('_coefffs shape: {}'.format(_coefffs.shape))
print(_coefffs)
print(len(foo_hat))
print(foo_hat.coeffs())
print(dir(foo_hat))

2
(2, 1000)
(1000,)
_coefffs shape: (10, 1)
[[ 5.00000000e-01]
 [-9.00000000e+00]
 [ 5.21804822e-15]
 [ 1.55431223e-15]
 [ 6.66133815e-16]
 [ 5.00000000e-01]
 [-3.00000000e+00]
 [ 1.05471187e-15]
 [ 2.22044605e-16]
 [ 8.88178420e-16]]
1
[ 1.55431223e-15  3.33066907e-15  1.49880108e-15  1.55431223e-15
  6.66133815e-16 -3.00000000e+00  1.05471187e-15  5.00000000e-01
  2.22044605e-16  8.88178420e-16]
['A', '__abs__', '__add__', '__array_priority__', '__call__', '__class__', '__contains__', '__delattr__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__pos__', '__pow__', '__radd__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__rsub__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__wea

In [14]:
doe_samples = np.array([x,w])
print(doe_samples.shape)

(2,)


In [15]:
numList = ['1', '2', '3', '4']
seperator = ', '
print(seperator.join(numList))

1, 2, 3, 4
