In [14]:
import numpy as np
import csv



In [2]:
a = np.arange(10).reshape(2,5)
print(a.size)
print(len(a))
print(a)
for ia in a:
    print(ia)
print([None,'1','h'])

10
2
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
[5 6 7 8 9]
[None, '1', 'h']


In [3]:
import pydoe

ModuleNotFoundError: No module named 'pydoe'

In [42]:
a = None
b = ['a','c']
c = np.array([1,2,3])
l1 = [None]
l2 = list(c)
l = l1 + l2
print(l)

[None, 1, 2, 3]


In [37]:
with open("result.txt", "wb") as result:
    writer = csv.writer(result, delimiter=';')
    writer.writerows(l)

Error: iterable expected, not int

In [43]:
with open('test1.text','w') as filein:
    filein.write('\t'.join(map(repr, l)))
    

In [39]:
with open('test1.text','r') as filein:
    for line in filein:
        x = line.split('\t')
        print(line)
        print(x)
        y = np.array(x[2]) * 2
        print(y)
        print(len(line))


1	2	3	None
['1', '2', '3', 'None']


TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')