In [1]:
import numpy as np
import csv
import chaospy as cp
import os
from datetime import datetime

In [2]:
from sklearn.gaussian_process.kernels import (RBF, Matern, RationalQuadratic,
                                              ExpSineSquared, DotProduct,
                                              ConstantKernel,WhiteKernel)


In [19]:
dir(RBF)
kernel = 1.0 * RBF(length_scale=100.0, length_scale_bounds=(1e-2, 1e3))
print(kernel)
# RBF.get_params()
# print(RBF.__str__)

1**2 * RBF(length_scale=100)


In [31]:
a = np.arange(3).T
print(a.shape)
b = a[:,np.newaxis]
print(b.shape)

(3,)
(3, 1)


In [8]:
dist_x = cp.Iid(cp.Uniform(),3)
print(type(cp.Normal()))
print(type(dist_x))

<class 'chaospy.distributions.cores.normal'>
<class 'chaospy.distributions.joint.Iid'>


In [6]:
def __num2str__(n):
    if n<100:
        return '{:2d}'.format(n)
    else:
        __str ='{:.0E}'.format(n) 
        return __str[0]+'E'+__str[-1] 
a = [100,10000,1000000]
b = list(map(__num2str__, a))

In [12]:
dataset = np.load('Train_Free_MCS1_DoE1.npy')
x, y, z = dataset
print(dataset.shape)
print(x.shape)
print(y.shape)
print(z.shape)

(3,)
(3, 100)
(100,)
(3, 100)


In [44]:
dist_x = cp.J(cp.Uniform(),cp.Uniform(),cp.Uniform())
samples = dist_x.sample(10000,rule='R')
print(dist_x)
print(samples)

J(Uniform(0,1),Uniform(0,1),Uniform(0,1))
[[0.54793665 0.4853775  0.38371563 ... 0.37988231 0.72600182 0.53662859]
 [0.21406472 0.64234094 0.44145543 ... 0.41955273 0.29831192 0.44337971]
 [0.29208272 0.88059741 0.51833234 ... 0.26899498 0.42106985 0.89066218]]


In [7]:
print(b)

['1E2', '1E4', '1E6']


In [30]:
a = np.arange(4).reshape(2,2)
b = np.arange(4).reshape(2,2)
# la = list(*(a[0,:])
lb = list(*(b[:,0])
# print(la)
print(lb)
# print(la+lb)

SyntaxError: invalid syntax (<ipython-input-30-602cd5600dcf>, line 6)

In [16]:
print(os.getcwd())
a = np.loadtxt('DoE_MC_R_10.txt')
b = np.loadtxt('/Users/jinsongliu/External/MUSE_UQ_DATA/Ishigami/Data/DoE_MC_R_10.txt')
print(a.shape)
a = np.load('DoE_MC_R_1E2.npy')
print(a.shape)

/Users/jinsongliu/BoxSync/MUSELab/museuq/examples
(10, 9)
(100, 6)


In [2]:
a = np.arange(10).reshape(2,5)
print(a.size)
print(len(a))
print(a)
for ia in a:
    print(ia)
print([None,'1','h'])

10
2
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
[5 6 7 8 9]
[None, '1', 'h']


In [15]:
now = datetime.now()
print(datetime.now())
dt_string = now.strftime("%d/%m/%Y %H:%M:%S")
print(dt_string)

2019-08-27 14:51:02.303020
27/08/2019 14:51:02


In [42]:
a = None
b = ['a','c']
c = np.array([1,2,3])
l1 = [None]
l2 = list(c)
l = l1 + l2
print(l)

[None, 1, 2, 3]


In [37]:
with open("result.txt", "wb") as result:
    writer = csv.writer(result, delimiter=';')
    writer.writerows(l)

Error: iterable expected, not int

In [43]:
with open('test1.text','w') as filein:
    filein.write('\t'.join(map(repr, l)))
    

In [39]:
with open('test1.text','r') as filein:
    for line in filein:
        x = line.split('\t')
        print(line)
        print(x)
        y = np.array(x[2]) * 2
        print(y)
        print(len(line))


1	2	3	None
['1', '2', '3', 'None']


TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')